name: CI/CD Pipeline

on:
  push:
    branches: [create/CICD]
  pull_request:
    branches: [create/CICD]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.18.0
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm run test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          # main 브랜치에 push될 때만 이미지를 push && github.ref == 'refs/heads/main' 
          push: ${{ github.event_name == 'push' }}
          # 태그를 latest와 함께 commit hash로 관리하여 추적성 확보
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/nestjs-app:latest
            ${{ secrets.DOCKER_USERNAME }}/nestjs-app:${{ github.sha }}
          # 빌드 속도 향상을 위한 캐시 설정
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
  
     #main 브랜치 push일 때만 CD 실행 ( 임시로 아니어도 실행가능 )
    if: github.event_name == 'push' #&& github.ref == 'refs/heads/main'

    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/nestjs-app:latest
      
            docker stop nestjs-app || true
            docker rm nestjs-app || true
      
            cat <<EOF > .env
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            JWT_TIME=${{ secrets.JWT_TIME }}
            EMAIL_ADDRESS=${{ secrets.EMAIL_ADDRESS }}
            EMAIL_PASS=${{ secrets.EMAIL_PASS }}
            REDIS_HOST=${{ secrets.REDIS_HOST }}
            REDIS_PORT=${{ secrets.REDIS_PORT }}
            REDIS_TTL=${{ secrets.REDIS_TTL }}
            DATABASE_HOST=${{ secrets.DATABASE_HOST }}
            DATABASE_PORT=${{ secrets.DATABASE_PORT }}
            DATABASE_USER=${{ secrets.DATABASE_USER }}
            DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}
            DATABASE_NAME=${{ secrets.DATABASE_NAME }}
            GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
            GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
            GOOGLE_CALLBACK_URL=${{ secrets.GOOGLE_CALLBACK_URL }}
            NAVER_CLIENT_ID=${{ secrets.NAVER_CLIENT_ID }}
            NAVER_CLIENT_SECRET=${{ secrets.NAVER_CLIENT_SECRET }}
            KAKAO_CLIENT_ID=${{ secrets.KAKAO_CLIENT_ID }}
            KAKAO_CLIENT_SECRET=${{ secrets.KAKAO_CLIENT_SECRET }}
            KAKAO_CALLBACK_URL=${{ secrets.KAKAO_CALLBACK_URL }}
            FASTAPI_URL=${{ secrets.FASTAPI_URL }}
            INTERNAL_JWT_SECRET=${{ secrets.INTERNAL_JWT_SECRET }}
            EOF
      
            docker run -d \
              --name nestjs-app \
              --env-file .env \
              -p 3000:3000 \
              --restart always \
              ${{ secrets.DOCKER_USERNAME }}/nestjs-app:latest
      
